services:
  - type: web
    name: civic-ai-services
    dockerfile: ./Dockerfile
    dockerfilePath: ./Dockerfile
    region: oregon
    plan: free
    envVars:
      - key: HF_TOKEN
        scope: run_and_build
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        scope: run_and_build
        sync: false
      - key: CLOUDINARY_API_KEY
        scope: run_and_build
        sync: false
      - key: CLOUDINARY_API_SECRET
        scope: run_and_build
        sync: false
      - key: GEMINI_API_KEY
        scope: run_and_build
        sync: false
      - key: FLASK_ENV
        value: production
